#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.17
# In conjunction with Tcl version 8.6
#    Oct 24, 2018 10:53:29 PM CST  platform: Windows NT

import sys

try:
    from Tkinter import *
except ImportError:
    from tkinter import *

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = Tk()
    top = About (root)
    root.resizable(width=False, height=False)
    root.iconbitmap("icon.ico")
    root.mainloop()

w = None
def create_About(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = Toplevel (root)
    top = About (w)
    return (w, top)

def destroy_About():
    global w
    w.destroy()
    w = None


class About:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85' 
        _ana2color = '#d9d9d9' # X11 color: 'gray85' 
        font10 = "-family {Courier New} -size 12 -weight normal -slant roman "  \
            "-underline 0 -overstrike 0"
        font12 = "-family {Times New Roman} -size 15 -weight normal "  \
            "-slant roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 13 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"
        font13 = "-family {Segoe UI} -size 12 -weight normal -slant roman" \
                " -underline 0 -overstrike 0"

        top.geometry("450x450+570+200")
        top.title("About")
        top.configure(background="#3818d8")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Labelframe1 = LabelFrame(top)
        self.Labelframe1.place(relx=0.011, rely=0.022, relheight=0.956
                , relwidth=0.978)
        self.Labelframe1.configure(relief=GROOVE)
        self.Labelframe1.configure(font=font9)
        self.Labelframe1.configure(foreground="#000000")
        self.Labelframe1.configure(labelanchor="n")
        self.Labelframe1.configure(text='''About My Vector and Matrix Calculator''')
        self.Labelframe1.configure(background="deep sky blue")
        self.Labelframe1.configure(highlightbackground="#d9d9d9")
        self.Labelframe1.configure(highlightcolor="black")
        self.Labelframe1.configure(width=440)

        self.Label1 = Label(self.Labelframe1)
        self.Label1.place(relx=0.034, rely=0.093, height=160, width=412
                          , bordermode='ignore')
        self.Label1.configure(background="deep sky blue")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(width=412)
        self.Label1.configure(font=font13)
        self.Label1.configure(justify =LEFT)
        self.Label1.configure(text = "My Vector and Matrix Calculator"
                                     "\n        Version 3.0(final version)"
                                     "\n--3D rotation(euler angle) added"
                                     "\n--fix icon for about")

        self.Label2 = Label(self.Labelframe1)
        self.Label2.place(relx=0.034, rely=0.500, height=100, width=412
                          , bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="deep sky blue")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font10)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(width=412)
        self.Label2.configure(text = "Created by : "
                                     "\nSahdan Chung"
                                     "\nChan Shen Zao"
                                     "\ncopyright(c) 2018 Niantic.co")

        self.Button1 = Button(self.Labelframe1)
        self.Button1.place(relx=0.432, rely=0.750, height=40, width=60
                , bordermode='ignore')
        self.Button1.configure(activebackground="#d9d9d9")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font12)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''OK''')
        self.Button1.configure(command = self.bttnOk)

    def bttnOk(self):
        root.destroy()





if __name__ == '__main__':
    vp_start_gui()



