# -*- mode: python -*-

block_cipher = None


a = Analysis(['main_menu.py'],
             pathex=['C:\\Users\\sahdan\\Desktop\\src'],
             binaries=[],
             datas=[('C:\\Users\\sahdan\\Desktop\\src\\Suspense Strike.wav','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\OpeningSound.wav','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\main_menu_bg.wav','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\ClickSound.wav','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\bgmusic.wav','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\binary.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\bg_logo.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_vector.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_transformation.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_series.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_matrix.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_composite.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_basic.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_back.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_4by4.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_3by3.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_2by2.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\icon.ico','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_2dv.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_3dv.png','.'),
             ('C:\\Users\\sahdan\\Desktop\\src\\b_3drotation.png','.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='My Vector and Matrix Calculator',
          debug=False,
          bootloader_ignore_signals=False,
          icon='C:\\Users\\sahdan\\Desktop\\src\\icon.ico',
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='application')
