from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.setFixedSize(1440, 1000)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/caditor.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("background-image: url(:/images/flowerbg.jfif);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 250, 1190, 650))
        self.frame.setStyleSheet("background-image: url(:/images/galacticbg.jpg);")
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_1 = QtWidgets.QLabel(self.frame)
        self.label_1.setGeometry(QtCore.QRect(40, 137, 500, 375))
        self.label_1.setStyleSheet("background-image: url(:/images/whitebg.jpg);")
        self.label_1.setText("")
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(650, 137, 500, 375))
        self.label_2.setStyleSheet("background-image: url(:/images/whitebg.jpg);")
        self.label_2.setText("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_original = QtWidgets.QLabel(self.frame)
        self.label_original.setGeometry(QtCore.QRect(0, 0, 590, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setWeight(9)
        self.label_original.setFont(font)
        self.label_original.setStyleSheet("color:rgb(255, 255, 255);\n"
                                          "background-color: rgb(2, 18, 44);\n"
                                          "font: 75 20pt \"Calibri\";")
        self.label_original.setAlignment(QtCore.Qt.AlignCenter)
        self.label_original.setObjectName("label_original")
        self.label_processed = QtWidgets.QLabel(self.frame)
        self.label_processed.setGeometry(QtCore.QRect(590, 0, 600, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_processed.setFont(font)
        self.label_processed.setStyleSheet("color:rgb(255, 255, 255);\n"
                                           "background-color: rgb(2, 18, 44);\n"
                                           "font: 75 20pt \"Calibri\";")
        self.label_processed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_processed.setObjectName("label_processed")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(595, 40, 1, 610))
        self.line.setStyleSheet("Color:rgb(170, 170, 0)")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.label_2.raise_()
        self.label_1.raise_()
        self.label_original.raise_()
        self.line.raise_()
        self.label_processed.raise_()
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1190, 900, 250, 74))
        self.pushButton.setStyleSheet("font: 75 18pt \"Tahoma\";\n""background-image: url(:/images/khaki.jpg);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon1)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setObjectName("pushButton")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(30, 30, 200, 200))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap(":/images/caditor.png"))
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1190, 250))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setObjectName("frame_2")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.frame_2)
        self.tabWidget_2.setGeometry(QtCore.QRect(230, 20, 950, 210))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget_2.setFont(font)
        self.tabWidget_2.setStyleSheet("background-color: rgb(85, 255, 127);\n"
"background-image: url(:/images/bluebg.jpg);")
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_resize = QtWidgets.QWidget()
        self.tab_resize.setObjectName("tab_resize")
        self.tabWidget_2.addTab(self.tab_resize, "")
        self.label_scale = QtWidgets.QLabel(self.tab_resize)
        self.label_scale.setGeometry(QtCore.QRect(190, 40, 220, 91))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(12)
        self.label_scale.setFont(font)
        self.label_scale.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_scale.setObjectName("label_scale")
        self.widthSlider = QtWidgets.QSlider(self.tab_resize)
        self.widthSlider.setGeometry(QtCore.QRect(400, 40, 211, 22))
        self.widthSlider.setMinimum(1)
        self.widthSlider.setMaximum(20)
        self.widthSlider.setSingleStep(1)
        self.widthSlider.setProperty("value", 10)
        self.widthSlider.setSliderPosition(10)
        self.widthSlider.setOrientation(QtCore.Qt.Horizontal)
        self.widthSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.widthSlider.setObjectName("widthSlider")
        self.heightSlider = QtWidgets.QSlider(self.tab_resize)
        self.heightSlider.setGeometry(QtCore.QRect(400, 90, 211, 22))
        self.heightSlider.setMinimum(1)
        self.heightSlider.setMaximum(20)
        self.heightSlider.setSingleStep(1)
        self.heightSlider.setProperty("value", 10)
        self.heightSlider.setSliderPosition(10)
        self.heightSlider.setOrientation(QtCore.Qt.Horizontal)
        self.heightSlider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.heightSlider.setObjectName("heightSlider")
        self.tab_rotate = QtWidgets.QWidget()
        self.tab_rotate.setObjectName("tab_rotate")
        self.b_rotateLeft = QtWidgets.QPushButton(self.tab_rotate)
        self.b_rotateLeft.setGeometry(QtCore.QRect(220, 15, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.b_rotateLeft.setFont(font)
        self.b_rotateLeft.setObjectName("b_rotateLeft")
        self.b_rotateRight = QtWidgets.QPushButton(self.tab_rotate)
        self.b_rotateRight.setGeometry(QtCore.QRect(400, 15, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.b_rotateRight.setFont(font)
        self.b_rotateRight.setObjectName("b_rotateRight")
        self.b_rotate180 = QtWidgets.QPushButton(self.tab_rotate)
        self.b_rotate180.setGeometry(QtCore.QRect(580, 15, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.b_rotate180.setFont(font)
        self.b_rotate180.setObjectName("b_rotate180")
        self.b_flipVertical = QtWidgets.QPushButton(self.tab_rotate)
        self.b_flipVertical.setGeometry(QtCore.QRect(200, 80, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.b_flipVertical.setFont(font)
        self.b_flipVertical.setObjectName("b_flipVertical")
        self.b_flipHori = QtWidgets.QPushButton(self.tab_rotate)
        self.b_flipHori.setGeometry(QtCore.QRect(600, 80, 150, 50))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.b_flipHori.setFont(font)
        self.b_flipHori.setObjectName("b_flipHori")
        self.rotateSlider = QtWidgets.QSlider(self.tab_rotate)
        self.rotateSlider.setGeometry(QtCore.QRect(364, 90, 221, 31))
        self.rotateSlider.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.rotateSlider.setMinimum(-360)
        self.rotateSlider.setMaximum(360)
        self.rotateSlider.setOrientation(QtCore.Qt.Horizontal)
        self.rotateSlider.setTickPosition(QtWidgets.QSlider.NoTicks)
        self.rotateSlider.setTickInterval(1)
        self.rotateSlider.setObjectName("rotateSlider")
        self.sliderLabel = QtWidgets.QLabel(self.tab_rotate)
        self.sliderLabel.setGeometry(QtCore.QRect(450, 130, 55, 21))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(13)
        self.sliderLabel.setFont(font)
        self.sliderLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.sliderLabel.setObjectName("sliderLabel")
        self.tabWidget_2.addTab(self.tab_rotate, "")
        self.tab_perspective = QtWidgets.QWidget()
        self.tab_perspective.setObjectName("tab_perspective")
        self.label_persp = QtWidgets.QLabel(self.tab_perspective)
        self.label_persp.setGeometry(QtCore.QRect(135, 30, 151, 121))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(11)
        self.label_persp.setFont(font)
        self.label_persp.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_persp.setObjectName("label_persp")
        self.label_persp_2 = QtWidgets.QLabel(self.tab_perspective)
        self.label_persp_2.setGeometry(QtCore.QRect(495, 30, 151, 121))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(11)
        self.label_persp_2.setFont(font)
        self.label_persp_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_persp_2.setObjectName("label_persp_2")
        self.topLeftx_silder = QtWidgets.QSlider(self.tab_perspective)
        self.topLeftx_silder.setGeometry(QtCore.QRect(305, 25, 150, 20))
        self.topLeftx_silder.setMinimum(-200)
        self.topLeftx_silder.setMaximum(200)
        self.topLeftx_silder.setSingleStep(10)
        self.topLeftx_silder.setOrientation(QtCore.Qt.Horizontal)
        self.topLeftx_silder.setObjectName("topLeftx_silder")
        self.topLefty_silder = QtWidgets.QSlider(self.tab_perspective)
        self.topLefty_silder.setGeometry(QtCore.QRect(305, 55, 150, 20))
        self.topLefty_silder.setMinimum(-200)
        self.topLefty_silder.setMaximum(200)
        self.topLefty_silder.setSingleStep(10)
        self.topLefty_silder.setOrientation(QtCore.Qt.Horizontal)
        self.topLefty_silder.setObjectName("topLefty_silder")
        self.bottomLeftx_silder = QtWidgets.QSlider(self.tab_perspective)
        self.bottomLeftx_silder.setGeometry(QtCore.QRect(305, 90, 150, 20))
        self.bottomLeftx_silder.setMinimum(-200)
        self.bottomLeftx_silder.setMaximum(200)
        self.bottomLeftx_silder.setSingleStep(10)
        self.bottomLeftx_silder.setOrientation(QtCore.Qt.Horizontal)
        self.bottomLeftx_silder.setObjectName("bottomLeftx_silder")
        self.bottomLefty_silder = QtWidgets.QSlider(self.tab_perspective)
        self.bottomLefty_silder.setGeometry(QtCore.QRect(305, 120, 150, 20))
        self.bottomLefty_silder.setMinimum(-200)
        self.bottomLefty_silder.setMaximum(200)
        self.bottomLefty_silder.setSingleStep(10)
        self.bottomLefty_silder.setOrientation(QtCore.Qt.Horizontal)
        self.bottomLefty_silder.setObjectName("bottomLefty_silder")
        self.topRightx_silder = QtWidgets.QSlider(self.tab_perspective)
        self.topRightx_silder.setGeometry(QtCore.QRect(665, 25, 150, 20))
        self.topRightx_silder.setMinimum(-200)
        self.topRightx_silder.setMaximum(200)
        self.topRightx_silder.setSingleStep(10)
        self.topRightx_silder.setOrientation(QtCore.Qt.Horizontal)
        self.topRightx_silder.setObjectName("topRightx_silder")
        self.topRighty_silder = QtWidgets.QSlider(self.tab_perspective)
        self.topRighty_silder.setGeometry(QtCore.QRect(665, 55, 150, 20))
        self.topRighty_silder.setMinimum(-200)
        self.topRighty_silder.setMaximum(200)
        self.topRighty_silder.setSingleStep(10)
        self.topRighty_silder.setOrientation(QtCore.Qt.Horizontal)
        self.topRighty_silder.setObjectName("topRighty_silder")
        self.bottomRightx_silder = QtWidgets.QSlider(self.tab_perspective)
        self.bottomRightx_silder.setGeometry(QtCore.QRect(665, 90, 150, 20))
        self.bottomRightx_silder.setMinimum(-200)
        self.bottomRightx_silder.setMaximum(200)
        self.bottomRightx_silder.setSingleStep(10)
        self.bottomRightx_silder.setOrientation(QtCore.Qt.Horizontal)
        self.bottomRightx_silder.setObjectName("bottomRightx_silder")
        self.bottomRighty_silder = QtWidgets.QSlider(self.tab_perspective)
        self.bottomRighty_silder.setGeometry(QtCore.QRect(665, 120, 150, 20))
        self.bottomRighty_silder.setMinimum(-200)
        self.bottomRighty_silder.setMaximum(200)
        self.bottomRighty_silder.setSingleStep(10)
        self.bottomRighty_silder.setOrientation(QtCore.Qt.Horizontal)
        self.bottomRighty_silder.setObjectName("bottomRighty_silder")
        self.tabWidget_2.addTab(self.tab_perspective, "")
        self.tab_binarymorphology = QtWidgets.QWidget()
        self.tab_binarymorphology.setObjectName("tab_binarymorphology")
        self.tab_dilationerosion = QtWidgets.QTabWidget(self.tab_binarymorphology)
        self.tab_dilationerosion.setGeometry(QtCore.QRect(44, 2, 851, 158))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.tab_dilationerosion.setFont(font)
        self.tab_dilationerosion.setObjectName("tab_dilationerosion")
        self.tab_dilation = QtWidgets.QWidget()
        self.tab_dilation.setObjectName("tab_dilation")
        self.label_dilationKernel = QtWidgets.QLabel(self.tab_dilation)
        self.label_dilationKernel.setGeometry(QtCore.QRect(90, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.label_dilationKernel.setFont(font)
        self.label_dilationKernel.setObjectName("label_dilationKernel")
        self.b_dilate = QtWidgets.QPushButton(self.tab_dilation)
        self.b_dilate.setGeometry(QtCore.QRect(640, 40, 100, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(15)
        self.b_dilate.setFont(font)
        self.b_dilate.setObjectName("b_dilate")
        self.dilation_slider = QtWidgets.QSlider(self.tab_dilation)
        self.dilation_slider.setGeometry(QtCore.QRect(340, 45, 170, 30))
        self.dilation_slider.setMinimum(1)
        self.dilation_slider.setMaximum(9)
        self.dilation_slider.setPageStep(1)
        self.dilation_slider.setSliderPosition(3)
        self.dilation_slider.setOrientation(QtCore.Qt.Horizontal)
        self.dilation_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.dilation_slider.setTickInterval(1)
        self.dilation_slider.setObjectName("dilation_slider")
        self.tab_dilationerosion.addTab(self.tab_dilation, "")
        self.tab_erosion = QtWidgets.QWidget()
        self.tab_erosion.setObjectName("tab_erosion")
        self.label_erosionKernel = QtWidgets.QLabel(self.tab_erosion)
        self.label_erosionKernel.setGeometry(QtCore.QRect(90, 40, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(15)
        self.label_erosionKernel.setFont(font)
        self.label_erosionKernel.setObjectName("label_erosionKernel")
        self.erosion_slider = QtWidgets.QSlider(self.tab_erosion)
        self.erosion_slider.setGeometry(QtCore.QRect(340, 45, 170, 30))
        self.erosion_slider.setMinimum(1)
        self.erosion_slider.setMaximum(9)
        self.erosion_slider.setPageStep(1)
        self.erosion_slider.setSliderPosition(3)
        self.erosion_slider.setOrientation(QtCore.Qt.Horizontal)
        self.erosion_slider.setTickPosition(QtWidgets.QSlider.TicksBothSides)
        self.erosion_slider.setTickInterval(1)
        self.erosion_slider.setObjectName("erosion_slider")
        self.b_erode = QtWidgets.QPushButton(self.tab_erosion)
        self.b_erode.setGeometry(QtCore.QRect(640, 40, 100, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(15)
        self.b_erode.setFont(font)
        self.b_erode.setObjectName("b_erode")
        self.tab_dilationerosion.addTab(self.tab_erosion, "")
        self.tabWidget_2.addTab(self.tab_binarymorphology, "")
        self.tab_splitmerge = QtWidgets.QWidget()
        self.tab_splitmerge.setObjectName("tab_splitmerge")
        self.tabSplitMerge = QtWidgets.QTabWidget(self.tab_splitmerge)
        self.tabSplitMerge.setGeometry(QtCore.QRect(10, 0, 921, 161))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabSplitMerge.setFont(font)
        self.tabSplitMerge.setObjectName("tabSplitMerge")
        self.tab_split = QtWidgets.QWidget()
        self.tab_split.setObjectName("tab_split")
        self.l_row = QtWidgets.QLabel(self.tab_split)
        self.l_row.setGeometry(QtCore.QRect(230, 30, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.l_row.setFont(font)
        self.l_row.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_row.setObjectName("l_row")
        self.spinBox_row = QtWidgets.QSpinBox(self.tab_split)
        self.spinBox_row.setGeometry(QtCore.QRect(340, 20, 50, 35))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.spinBox_row.setFont(font)
        self.spinBox_row.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_row.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_row.setMinimum(1)
        self.spinBox_row.setMaximum(10)
        self.spinBox_row.setProperty("value", 1)
        self.spinBox_row.setObjectName("spinBox_row")
        self.l_column = QtWidgets.QLabel(self.tab_split)
        self.l_column.setGeometry(QtCore.QRect(230, 80, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.l_column.setFont(font)
        self.l_column.setAlignment(QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.l_column.setObjectName("l_column")
        self.spinBox_column = QtWidgets.QSpinBox(self.tab_split)
        self.spinBox_column.setGeometry(QtCore.QRect(340, 70, 50, 35))
        font = QtGui.QFont()
        font.setFamily("Cambria Math")
        font.setPointSize(12)
        self.spinBox_column.setFont(font)
        self.spinBox_column.setAlignment(QtCore.Qt.AlignCenter)
        self.spinBox_column.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.spinBox_column.setMinimum(1)
        self.spinBox_column.setMaximum(10)
        self.spinBox_column.setProperty("value", 1)
        self.spinBox_column.setObjectName("spinBox_column")
        self.splitButton = QtWidgets.QPushButton(self.tab_split)
        self.splitButton.setGeometry(QtCore.QRect(500, 45, 100, 35))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.splitButton.setFont(font)
        self.splitButton.setObjectName("splitButton")
        self.line_cbox = QtWidgets.QComboBox(self.tab_split)
        self.line_cbox.setGeometry(QtCore.QRect(80, 40, 120, 35))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.line_cbox.setFont(font)
        self.line_cbox.setObjectName("line_cbox")
        self.line_cbox.addItem("")
        self.line_cbox.addItem("")
        self.line_cbox.addItem("")
        self.line_cbox.addItem("")
        self.saveSplit = QtWidgets.QPushButton(self.tab_split)
        self.saveSplit.setGeometry(QtCore.QRect(660, 40, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(14)
        self.saveSplit.setFont(font)
        self.saveSplit.setObjectName("saveSplit")
        self.tabSplitMerge.addTab(self.tab_split, "")
        self.tab_merge = QtWidgets.QWidget()
        self.tab_merge.setObjectName("tab_merge")
        self.count_cbox = QtWidgets.QComboBox(self.tab_merge)
        self.count_cbox.setGeometry(QtCore.QRect(20, 40, 141, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.count_cbox.setFont(font)
        self.count_cbox.setObjectName("count_cbox")
        self.count_cbox.addItem("")
        self.count_cbox.addItem("")
        self.count_cbox.addItem("")
        self.count_cbox.addItem("")
        self.label_img2 = QtWidgets.QLabel(self.tab_merge)
        self.label_img2.setGeometry(QtCore.QRect(180, 10, 100, 75))
        self.label_img2.setStyleSheet("background-image: url(:/images/whitebg.jpg);")
        self.label_img2.setText("")
        self.label_img2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img2.setObjectName("label_img2")
        self.label_img3 = QtWidgets.QLabel(self.tab_merge)
        self.label_img3.setGeometry(QtCore.QRect(300, 10, 100, 75))
        self.label_img3.setStyleSheet("background-image: url(:/images/whitebg.jpg);")
        self.label_img3.setText("")
        self.label_img3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img3.setObjectName("label_img3")
        self.label_img4 = QtWidgets.QLabel(self.tab_merge)
        self.label_img4.setGeometry(QtCore.QRect(420, 10, 100, 75))
        self.label_img4.setStyleSheet("background-image: url(:/images/whitebg.jpg);")
        self.label_img4.setText("")
        self.label_img4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img4.setObjectName("label_img4")
        self.load_img2 = QtWidgets.QPushButton(self.tab_merge)
        self.load_img2.setGeometry(QtCore.QRect(185, 90, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_img2.setFont(font)
        self.load_img2.setObjectName("load_img2")
        self.load_img3 = QtWidgets.QPushButton(self.tab_merge)
        self.load_img3.setGeometry(QtCore.QRect(305, 90, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_img3.setFont(font)
        self.load_img3.setObjectName("load_img3")
        self.load_img4 = QtWidgets.QPushButton(self.tab_merge)
        self.load_img4.setGeometry(QtCore.QRect(425, 90, 90, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.load_img4.setFont(font)
        self.load_img4.setObjectName("load_img4")
        self.label_img2.setVisible(False)
        self.label_img3.setVisible(False)
        self.label_img4.setVisible(False)
        self.load_img2.setVisible(False)
        self.load_img3.setVisible(False)
        self.load_img4.setVisible(False)
        self.merge_cbox = QtWidgets.QComboBox(self.tab_merge)
        self.merge_cbox.setGeometry(QtCore.QRect(540, 40, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(13)
        self.merge_cbox.setFont(font)
        self.merge_cbox.setObjectName("merge_cbox")
        self.merge_cbox.addItem("")
        self.merge_cbox.addItem("")
        self.merge_cbox.addItem("")
        self.merge_button = QtWidgets.QPushButton(self.tab_merge)
        self.merge_button.setGeometry(QtCore.QRect(765, 40, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(15)
        self.merge_button.setFont(font)
        self.merge_button.setObjectName("merge_button")

        self.tabSplitMerge.addTab(self.tab_merge, "")
        self.tabWidget_2.addTab(self.tab_splitmerge, "")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(1190, 0, 250, 900))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("border-color: rgb(0, 0, 0);")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setObjectName("tabWidget")
        self.Effects = QtWidgets.QWidget()
        self.Effects.setObjectName("Effects")
        self.toolBox = QtWidgets.QToolBox(self.Effects)
        self.toolBox.setGeometry(QtCore.QRect(40, 50, 171, 791))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox.setFont(font)
        self.toolBox.setStyleSheet("background-image: url(:/images/blue_pastel.jpg);")
        self.toolBox.setObjectName("toolBox")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setGeometry(QtCore.QRect(0, 0, 171, 461))
        self.page_1.setObjectName("page_1")
        self.b_grayscale = QtWidgets.QPushButton(self.page_1)
        self.b_grayscale.setGeometry(QtCore.QRect(5, 100, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_grayscale.setFont(font)
        self.b_grayscale.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/images/khaki.jpg);\n")
        self.b_grayscale.setObjectName("b_grayscale")
        self.toolBox.addItem(self.page_1, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 171, 461))
        self.page_2.setObjectName("page_2")
        self.b_hsv = QtWidgets.QPushButton(self.page_2)
        self.b_hsv.setGeometry(QtCore.QRect(5, 150, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_hsv.setFont(font)
        self.b_hsv.setStyleSheet("color: rgb(0, 0, 0);\n"
                                 "background-image: url(:/images/khaki.jpg);\n")
        self.b_hsv.setObjectName("b_hsv")
        self.toolBox.addItem(self.page_2, "")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setGeometry(QtCore.QRect(0, 0, 171, 461))
        self.page_3.setObjectName("page_3")
        self.b_negative = QtWidgets.QPushButton(self.page_3)
        self.b_negative.setGeometry(QtCore.QRect(5, 160, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_negative.setFont(font)
        self.b_negative.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/images/khaki.jpg);\n"
"")
        self.b_negative.setObjectName("b_negative")
        self.toolBox.addItem(self.page_3, "")
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setGeometry(QtCore.QRect(0, 0, 171, 461))
        self.page_4.setObjectName("page_4")
        self.b_binary = QtWidgets.QPushButton(self.page_4)
        self.b_binary.setGeometry(QtCore.QRect(5, 10, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_binary.setFont(font)
        self.b_binary.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/images/khaki.jpg);")
        self.b_binary.setObjectName("b_binary")
        self.b_binaryInv = QtWidgets.QPushButton(self.page_4)
        self.b_binaryInv.setGeometry(QtCore.QRect(5, 95, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_binaryInv.setFont(font)
        self.b_binaryInv.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/images/khaki.jpg);\n")
        self.b_binaryInv.setObjectName("b_binaryInv")
        self.b_binarytrunc = QtWidgets.QPushButton(self.page_4)
        self.b_binarytrunc.setGeometry(QtCore.QRect(5, 180, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_binarytrunc.setFont(font)
        self.b_binarytrunc.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/images/khaki.jpg);\n")
        self.b_binarytrunc.setObjectName("b_binarytrunc")
        self.b_binarytozero = QtWidgets.QPushButton(self.page_4)
        self.b_binarytozero.setGeometry(QtCore.QRect(5, 265, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_binarytozero.setFont(font)
        self.b_binarytozero.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/images/khaki.jpg);\n")
        self.b_binarytozero.setObjectName("b_binarytozero")
        self.b_binarytozeroInv = QtWidgets.QPushButton(self.page_4)
        self.b_binarytozeroInv.setGeometry(QtCore.QRect(5, 350, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_binarytozeroInv.setFont(font)
        self.b_binarytozeroInv.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-image: url(:/images/khaki.jpg);\n")
        self.b_binarytozeroInv.setObjectName("b_binarytozeroInv")
        self.toolBox.addItem(self.page_4, "")
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.b_roi1 = QtWidgets.QPushButton(self.page_5)
        self.b_roi1.setGeometry(QtCore.QRect(7, 50, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_roi1.setFont(font)
        self.b_roi1.setStyleSheet("color: rgb(0, 0, 0);\n"
                                  "background-image: url(:/images/khaki.jpg);\n"
                                  "")
        self.b_roi1.setObjectName("b_roi1")
        self.b_roi2 = QtWidgets.QPushButton(self.page_5)
        self.b_roi2.setGeometry(QtCore.QRect(7, 160, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_roi2.setFont(font)
        self.b_roi2.setStyleSheet("color: rgb(0, 0, 0);\n"
                                  "background-image: url(:/images/khaki.jpg);\n"
                                  "")
        self.b_roi2.setObjectName("b_roi2")
        self.toolBox.addItem(self.page_5, "")
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.b_halftone = QtWidgets.QPushButton(self.page_6)
        self.b_halftone.setGeometry(QtCore.QRect(5, 110, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_halftone.setFont(font)
        self.b_halftone.setStyleSheet("color: rgb(0, 0, 0);\n"
                                      "background-image: url(:/images/khaki.jpg);\n"
                                      "")
        self.b_halftone.setObjectName("b_halftone")
        self.toolBox.addItem(self.page_6, "")
        self.tabWidget.addTab(self.Effects, "")
        self.Filter = QtWidgets.QWidget()
        self.Filter.setObjectName("Filter")
        self.tabWidget.addTab(self.Filter, "")
        self.frame_2.raise_()
        self.frame.raise_()
        self.pushButton.raise_()
        self.logo.raise_()
        self.tabWidget.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1440, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(11)
        self.menuBar.setFont(font)
        self.menuBar.setStyleSheet("color: rgb(0, 0, 0);")
        self.menuBar.setObjectName("menuBar")
        self.menu_File = QtWidgets.QMenu(self.menuBar)
        self.menu_File.setObjectName("menu_File")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuHistogram = QtWidgets.QMenu(self.menuBar)
        self.menuHistogram.setObjectName("menuHistogram")
        self.actionOriginal = QtWidgets.QAction(MainWindow)
        self.actionOriginal.setObjectName("actionOriginal")
        self.actionProcessed = QtWidgets.QAction(MainWindow)
        self.actionProcessed.setObjectName("actionProcessed")
        self.actionEqualization = QtWidgets.QAction(MainWindow)
        self.actionEqualization.setObjectName("actionEqualization")
        MainWindow.setMenuBar(self.menuBar)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/open.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setIcon(icon2)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit_2 = QtWidgets.QAction(MainWindow)
        self.actionExit_2.setIcon(icon3)
        self.actionExit_2.setObjectName("actionExit_2")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menu_File.addAction(self.actionOpen)
        self.menu_File.addAction(self.actionExit_2)
        self.menuHistogram.addAction(self.actionOriginal)
        self.menuHistogram.addAction(self.actionProcessed)
        self.menuHistogram.addAction(self.actionEqualization)
        self.menuHelp.addAction(self.actionAbout)
        self.menuBar.addAction(self.menu_File.menuAction())
        self.menuBar.addAction(self.menuHistogram.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.b_reset = QtWidgets.QPushButton(self.frame)
        self.b_reset.setGeometry(QtCore.QRect(1030, 575, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Semibold")
        font.setPointSize(25)
        self.b_reset.setFont(font)
        self.b_reset.setStyleSheet("color: rgb(0, 0, 0);\n"
                                   "background-image: url(:/images/khaki.jpg);\n")
        self.b_reset.setObjectName("b_reset")
        self.label_imgproperty = QtWidgets.QLabel(self.frame)
        self.label_imgproperty.setGeometry(QtCore.QRect(180, 540, 211, 91))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        self.label_imgproperty.setFont(font)
        self.label_imgproperty.setStyleSheet("background-image: url(:/images/khaki.jpg);\n")
        self.label_imgproperty.setText("")
        self.label_imgproperty.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignTop)
        self.label_imgproperty.setObjectName("label_imgproperty")
        self.label_imgproperty.setVisible(False)
        self.b_reset.raise_()
        self.label_imgproperty.raise_()
        self.toolBox_2 = QtWidgets.QToolBox(self.Filter)
        self.toolBox_2.setGeometry(QtCore.QRect(40, 50, 180, 701))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.toolBox_2.setFont(font)
        self.toolBox_2.setStyleSheet("background-image: url(:/images/blue_pastel.jpg);")
        self.toolBox_2.setObjectName("toolBox_2")
        self.page_convolution = QtWidgets.QWidget()
        self.page_convolution.setGeometry(QtCore.QRect(0, 0, 180, 513))
        self.page_convolution.setObjectName("page_convolution")
        self.b_convolution = QtWidgets.QPushButton(self.page_convolution)
        self.b_convolution.setGeometry(QtCore.QRect(10, 100, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(13)
        self.b_convolution.setFont(font)
        self.b_convolution.setStyleSheet("color: rgb(0, 0, 0);\n"
                                         "background-image: url(:/images/khaki.jpg);\n")
        self.b_convolution.setObjectName("b_convolution")
        self.toolBox_2.addItem(self.page_convolution, "")
        self.page_averaging = QtWidgets.QWidget()
        self.page_averaging.setGeometry(QtCore.QRect(0, 0, 180, 513))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.page_averaging.setFont(font)
        self.page_averaging.setObjectName("page_averaging")
        self.b_averaging = QtWidgets.QPushButton(self.page_averaging)
        self.b_averaging.setGeometry(QtCore.QRect(10, 70, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_averaging.setFont(font)
        self.b_averaging.setStyleSheet("color: rgb(0, 0, 0);\n"
                                       "background-image: url(:/images/khaki.jpg);\n")
        self.b_averaging.setObjectName("b_averaging")
        self.toolBox_2.addItem(self.page_averaging, "")
        self.page_median = QtWidgets.QWidget()
        self.page_median.setGeometry(QtCore.QRect(0, 0, 180, 466))
        self.page_median.setObjectName("page_median")
        self.b_median = QtWidgets.QPushButton(self.page_median)
        self.b_median.setGeometry(QtCore.QRect(10, 180, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_median.setFont(font)
        self.b_median.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "background-image: url(:/images/khaki.jpg);\n")
        self.b_median.setObjectName("b_median")
        self.median_kernel = QtWidgets.QLabel(self.page_median)
        self.median_kernel.setGeometry(QtCore.QRect(40, 20, 110, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.median_kernel.setFont(font)
        self.median_kernel.setStyleSheet("background-image: url(:/images/khaki.jpg);")
        self.median_kernel.setAlignment(QtCore.Qt.AlignCenter)
        self.median_kernel.setObjectName("median_kernel")
        self.median_slider = QtWidgets.QSlider(self.page_median)
        self.median_slider.setGeometry(QtCore.QRect(10, 120, 160, 22))
        self.median_slider.setStyleSheet("background-image: url(:/images/khaki.jpg);")
        self.median_slider.setMinimum(1)
        self.median_slider.setSliderPosition(5)
        self.median_slider.setOrientation(QtCore.Qt.Horizontal)
        self.median_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.median_slider.setObjectName("median_slider")
        self.toolBox_2.addItem(self.page_median, "")
        self.page_bilateral = QtWidgets.QWidget()
        self.page_bilateral.setGeometry(QtCore.QRect(0, 0, 180, 466))
        self.page_bilateral.setObjectName("page_bilateral")
        self.b_bilateral = QtWidgets.QPushButton(self.page_bilateral)
        self.b_bilateral.setGeometry(QtCore.QRect(10, 180, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_bilateral.setFont(font)
        self.b_bilateral.setStyleSheet("color: rgb(0, 0, 0);\n"
                                       "background-image: url(:/images/khaki.jpg);\n")
        self.b_bilateral.setObjectName("b_bilateral")
        self.bilateral_kernel = QtWidgets.QLabel(self.page_bilateral)
        self.bilateral_kernel.setGeometry(QtCore.QRect(5, 30, 170, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bilateral_kernel.setFont(font)
        self.bilateral_kernel.setStyleSheet("background-image: url(:/images/khaki.jpg);")
        self.bilateral_kernel.setAlignment(QtCore.Qt.AlignCenter)
        self.bilateral_kernel.setObjectName("bilateral_kernel")
        self.bilateral_slider = QtWidgets.QSlider(self.page_bilateral)
        self.bilateral_slider.setGeometry(QtCore.QRect(10, 110, 160, 22))
        self.bilateral_slider.setStyleSheet("background-image: url(:/images/khaki.jpg);")
        self.bilateral_slider.setMinimum(1)
        self.bilateral_slider.setSliderPosition(75)
        self.bilateral_slider.setOrientation(QtCore.Qt.Horizontal)
        self.bilateral_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.bilateral_slider.setObjectName("bilateral_slider")
        self.toolBox_2.addItem(self.page_bilateral, "")
        self.page_gaussian = QtWidgets.QWidget()
        self.page_gaussian.setObjectName("page_gaussian")
        self.b_gaussian = QtWidgets.QPushButton(self.page_gaussian)
        self.b_gaussian.setGeometry(QtCore.QRect(10, 190, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_gaussian.setFont(font)
        self.b_gaussian.setStyleSheet("color: rgb(0, 0, 0);\n"
                                      "background-image: url(:/images/khaki.jpg);\n")
        self.b_gaussian.setObjectName("b_gaussian")
        self.gaussian_kernel = QtWidgets.QLabel(self.page_gaussian)
        self.gaussian_kernel.setGeometry(QtCore.QRect(15, 20, 160, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.gaussian_kernel.setFont(font)
        self.gaussian_kernel.setStyleSheet("background-image: url(:/images/khaki.jpg);")
        self.gaussian_kernel.setAlignment(QtCore.Qt.AlignCenter)
        self.gaussian_kernel.setObjectName("gaussian_kernel")
        self.gaussian_slider = QtWidgets.QSlider(self.page_gaussian)
        self.gaussian_slider.setGeometry(QtCore.QRect(10, 120, 160, 22))
        self.gaussian_slider.setStyleSheet("background-image: url(:/images/khaki.jpg);")
        self.gaussian_slider.setMinimum(1)
        self.gaussian_slider.setSliderPosition(5)
        self.gaussian_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gaussian_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gaussian_slider.setObjectName("gaussian_slider")
        self.toolBox_2.addItem(self.page_gaussian, "")
        self.page_laplacian = QtWidgets.QWidget()
        self.page_laplacian.setObjectName("page_laplacian")
        self.b_laplacian = QtWidgets.QPushButton(self.page_laplacian)
        self.b_laplacian.setGeometry(QtCore.QRect(10, 120, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_laplacian.setFont(font)
        self.b_laplacian.setStyleSheet("color: rgb(0, 0, 0);\n"
                                       "background-image: url(:/images/khaki.jpg);\n")
        self.b_laplacian.setObjectName("b_laplacian")
        self.toolBox_2.addItem(self.page_laplacian, "")
        self.page_sobelx = QtWidgets.QWidget()
        self.page_sobelx.setObjectName("page_sobelx")
        self.b_sobelx = QtWidgets.QPushButton(self.page_sobelx)
        self.b_sobelx.setGeometry(QtCore.QRect(10, 110, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_sobelx.setFont(font)
        self.b_sobelx.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "background-image: url(:/images/khaki.jpg);\n")
        self.b_sobelx.setObjectName("b_sobelx")
        self.toolBox_2.addItem(self.page_sobelx, "")
        self.page_sobely = QtWidgets.QWidget()
        self.page_sobely.setObjectName("page_sobely")
        self.b_sobely = QtWidgets.QPushButton(self.page_sobely)
        self.b_sobely.setGeometry(QtCore.QRect(10, 80, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_sobely.setFont(font)
        self.b_sobely.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "background-image: url(:/images/khaki.jpg);\n")
        self.b_sobely.setObjectName("b_sobely")
        self.toolBox_2.addItem(self.page_sobely, "")
        self.page_edge = QtWidgets.QWidget()
        self.page_edge.setObjectName("page_edge")
        self.b_cannye = QtWidgets.QPushButton(self.page_edge)
        self.b_cannye.setGeometry(QtCore.QRect(10, 10, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_cannye.setFont(font)
        self.b_cannye.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "background-image: url(:/images/khaki.jpg);\n"
                                    "")
        self.b_cannye.setObjectName("b_cannye")
        self.b_sobele = QtWidgets.QPushButton(self.page_edge)
        self.b_sobele.setGeometry(QtCore.QRect(10, 95, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_sobele.setFont(font)
        self.b_sobele.setStyleSheet("color: rgb(0, 0, 0);\n"
                                    "background-image: url(:/images/khaki.jpg);\n"
                                    "")
        self.b_sobele.setObjectName("b_sobele")
        self.b_prewitte = QtWidgets.QPushButton(self.page_edge)
        self.b_prewitte.setGeometry(QtCore.QRect(10, 180, 160, 75))
        font = QtGui.QFont()
        font.setFamily("Sitka Text")
        font.setPointSize(15)
        self.b_prewitte.setFont(font)
        self.b_prewitte.setStyleSheet("color: rgb(0, 0, 0);\n"
                                      "background-image: url(:/images/khaki.jpg);\n"
                                      "")
        self.b_prewitte.setObjectName("b_prewitte")
        self.toolBox_2.addItem(self.page_edge, "")

        self.retranslateUi(MainWindow)
        self.tabWidget_2.setCurrentIndex(0)
        self.tab_dilationerosion.setCurrentIndex(0)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Simple Image Editor"))
        self.label_original.setText(_translate("MainWindow", "Original"))
        self.label_processed.setText(_translate("MainWindow", "Processed"))
        self.pushButton.setText(_translate("MainWindow", "Save As..."))
        self.label_scale.setText(_translate("MainWindow", "Width Scale\t=\n\nHeight Scale\t="))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_resize), _translate("MainWindow", "Resize"))
        self.b_rotateLeft.setText(_translate("MainWindow", "Rotate Left 90°"))
        self.b_rotateRight.setText(_translate("MainWindow", "Rotate Right 90°"))
        self.b_rotate180.setText(_translate("MainWindow", "Rotate 180°"))
        self.b_flipVertical.setText(_translate("MainWindow", "Flip Vertical"))
        self.b_flipHori.setText(_translate("MainWindow", "Flip Horizontal"))
        self.sliderLabel.setText(_translate("MainWindow", "0°"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_rotate), _translate("MainWindow", "Rotate"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_perspective),
                                    _translate("MainWindow", "Perspective"))
        self.label_persp.setText(_translate("MainWindow", "topLeft_x\t:\n"
                                                          "topLeft_y\t:\n\n"
                                                          "bottomLeft_x\t:\n"
                                                          "bottomLeft_y\t:"))
        self.label_persp_2.setText(_translate("MainWindow", "topRight_x\t:\n"
                                                            "topRight_y\t:\n\n"
                                                            "bottomRight_x\t:\n"
                                                            "bottomRight_y\t:"))
        self.label_dilationKernel.setText(_translate("MainWindow", "kernel = (3 , 3)"))
        self.b_dilate.setText(_translate("MainWindow", "Dilate"))
        self.tab_dilationerosion.setTabText(self.tab_dilationerosion.indexOf(self.tab_dilation),
                                            _translate("MainWindow", "Dilation"))
        self.label_erosionKernel.setText(_translate("MainWindow", "kernel = (3 , 3)"))
        self.b_erode.setText(_translate("MainWindow", "Erode"))
        self.tab_dilationerosion.setTabText(self.tab_dilationerosion.indexOf(self.tab_erosion),
                                            _translate("MainWindow", "Erosion"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_binarymorphology),
                                    _translate("MainWindow", "Binary Morphology"))
        self.l_row.setText(_translate("MainWindow", "Row"))
        self.l_column.setText(_translate("MainWindow", "Column"))
        self.splitButton.setText(_translate("MainWindow", "Split"))
        self.line_cbox.setItemText(0, _translate("MainWindow", "yellow"))
        self.line_cbox.setItemText(1, _translate("MainWindow", "black"))
        self.line_cbox.setItemText(2, _translate("MainWindow", "white"))
        self.line_cbox.setItemText(3, _translate("MainWindow", "green"))
        self.saveSplit.setText(_translate("MainWindow", "save split image"))
        self.tabSplitMerge.setTabText(self.tabSplitMerge.indexOf(self.tab_split),
                                      _translate("MainWindow", "Split Image"))
        self.count_cbox.setItemText(0, _translate("MainWindow", "number of image"))
        self.count_cbox.setItemText(1, _translate("MainWindow", "2"))
        self.count_cbox.setItemText(2, _translate("MainWindow", "3"))
        self.count_cbox.setItemText(3, _translate("MainWindow", "4"))
        self.load_img2.setText(_translate("MainWindow", "load"))
        self.load_img3.setText(_translate("MainWindow", "load"))
        self.load_img4.setText(_translate("MainWindow", "load"))
        self.merge_cbox.setItemText(0, _translate("MainWindow", "select merge type"))
        self.merge_cbox.setItemText(1, _translate("MainWindow", "Horizontal"))
        self.merge_cbox.setItemText(2, _translate("MainWindow", "Vertical"))
        self.merge_button.setText(_translate("MainWindow", "Merge"))
        self.tabSplitMerge.setTabText(self.tabSplitMerge.indexOf(self.tab_merge),
                                      _translate("MainWindow", "Merge Image"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_splitmerge),
                                    _translate("MainWindow", "Split,Merge"))
        self.b_grayscale.setText(_translate("MainWindow", "change to \n"
                                                          "grayscale"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_1), _translate("MainWindow", "Grayscale"))
        self.b_hsv.setText(_translate("MainWindow", "change to \n"
                                                    "HSV"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "   HSV"))
        self.b_negative.setText(_translate("MainWindow", "change to \n"
                                                         "negative"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_3), _translate("MainWindow", " Negative"))
        self.b_binary.setText(_translate("MainWindow", "binary"))
        self.b_binaryInv.setText(_translate("MainWindow", "binary,\n"
                                                          "inverted"))
        self.b_binarytrunc.setText(_translate("MainWindow", "binary, \n"
                                                            "truncate"))
        self.b_binarytozero.setText(_translate("MainWindow", "to Zero"))
        self.b_binarytozeroInv.setText(_translate("MainWindow", "to Zero, \n"
                                                                "inverted"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_4), _translate("MainWindow", "Threshold"))
        self.b_roi1.setText(_translate("MainWindow", "Select region"))
        self.b_roi2.setText(_translate("MainWindow", "auto ROI"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_5), _translate("MainWindow", "   ROI"))
        self.b_halftone.setText(_translate("MainWindow", "Change to\n"
                                                         "halftone"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_6), _translate("MainWindow", " Halftone"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Effects), _translate("MainWindow", "Effects"))
        self.b_convolution.setText(_translate("MainWindow", "filter to \n"
                                                            "2D convolution"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_convolution),
                                   _translate("MainWindow", "2D Convolution"))
        self.b_averaging.setText(_translate("MainWindow", "filter to \n"
                                                          "averaging"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_averaging),
                                   _translate("MainWindow", "   Averaging"))
        self.b_median.setText(_translate("MainWindow", "filter to \n"
                                                       "median"))
        self.median_kernel.setText(_translate("MainWindow", "kernel = 5"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_median), _translate("MainWindow", "     Median"))
        self.b_bilateral.setText(_translate("MainWindow", "filter to\n"
                                                          "bilateral"))
        self.bilateral_kernel.setText(_translate("MainWindow", "kernel = (75, 75)"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_bilateral),
                                   _translate("MainWindow", "    Bilateral"))
        self.b_gaussian.setText(_translate("MainWindow", "filter to\n"
                                                         "gaussian"))
        self.gaussian_kernel.setText(_translate("MainWindow", "kernel = (5, 5)"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_gaussian), _translate("MainWindow", "    Gaussian"))
        self.b_laplacian.setText(_translate("MainWindow", "filter to\n"
                                                          "laplacian"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_laplacian),
                                   _translate("MainWindow", "    Laplacian"))
        self.b_sobelx.setText(_translate("MainWindow", "filter to\n"
                                                       "sobel_x"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_sobelx), _translate("MainWindow", "    Sobel_x"))
        self.b_sobely.setText(_translate("MainWindow", "filter to\n"
                                                       "sobel_y"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_sobely), _translate("MainWindow", "    Sobel_y"))
        self.b_cannye.setText(_translate("MainWindow", "Canny edge"))
        self.b_sobele.setText(_translate("MainWindow", "Sobel edge"))
        self.b_prewitte.setText(_translate("MainWindow", "Prewitt edge"))
        self.toolBox_2.setItemText(self.toolBox_2.indexOf(self.page_edge), _translate("MainWindow", "Edge detection"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Filter), _translate("MainWindow", "Filter"))
        self.menu_File.setTitle(_translate("MainWindow", "File"))
        self.menuHistogram.setTitle(_translate("MainWindow", "Histogram"))
        self.actionOriginal.setText(_translate("MainWindow", "Original"))
        self.actionProcessed.setText(_translate("MainWindow", "Processed"))
        self.actionEqualization.setText(_translate("MainWindow", "Equalization"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open.."))
        self.actionExit_2.setText(_translate("MainWindow", "Exit.."))
        self.b_reset.setText(_translate("MainWindow", "Reset "))
        self.label_imgproperty.setText(_translate("MainWindow", " "))
        self.actionAbout.setText(_translate("MainWindow", "About"))
